### ISSUE TITLE
High crash rate on Gogle Play Console

### ISSUE THREAD

**Issue by huyptmaxmobile** [yandexmobile/yandex-ads-sdk-android#214]
Hello,
We started implementing Yandex Mobile Ads recently in parallel with Google Admob. We use Google Mobile Ads SDK and Yandex Mobile Ads SDK separately, not mediation.
Most of the applications are still running fine with no errors since applying Yandex Mobile Ads. However, there are 2 applications that receive unusual crash reports on Google Play Console (not on Crashlytics), about 5-7% (Very large number) with this same error:
```
*** *** *** *** *** *** *** *** *** *** *** *** *** *** ***
pid: 0, tid: 18132 >>> com.xxx.xxx<<<

backtrace:
   #00 pc 0x000000000005c310
   #01 pc 0x0000000000058838 /data/data/com.xxx.xxx/app_pccache/5/7B8F7DD4852F73BBFA173EB6B41A78FEF0FC34F5/pcam.jar

```
![image](https://github.com/yandexmobile/yandex-ads-sdk-android/assets/83760091/1cba4e6c-a00b-43fb-ba5f-1696558ffece)
![image](https://github.com/yandexmobile/yandex-ads-sdk-android/assets/83760091/9e5dedb8-48ae-48d5-af49-5384bf2e695c)

We are using Google Mobile Ads SDK v21.3.0. When we found the error we were using Yandex Mobile Ads SDK v5.7.0, we tried to upgrade to v5.8.0 and target SDK 33 but the error persisted.

Please help us fix this, if we can't solve this we will probably have to remove Yandex Ads in future updates.

Thank you!

**Comment by AppMetricaSupport** [comment]
Добрый день!Ваше письмо получено и зарегистрировано под уникальным номером № 25064800. Ответ обязательно будет предоставлен, пожалуйста, ожидайте.Просим Вас не отправлять повторное письмо по данному вопросу - оно будет считаться новой заявкой и может быть обработано позднее.Помощь сервиса: https://yandex.ru/support/direct/?from=email--С уважением,Отдел клиентского сервисател.: 8 800 234-24-80 (звонок из регионов России бесплатный)тел.: +7 495 739-37-77&nbsp06.07.2023, 08:06, "huyptmaxmobile" ***@***.***>:
Hello,
We started implementing Yandex Mobile Ads recently in parallel with Google Admob. We use Google Mobile Ads SDK and Yandex Mobile Ads SDK separately, not mediation.
Most of the applications are still running fine with no errors since applying Yandex Mobile Ads. However, there are 2 applications that receive unusual crash reports on Google Play Console (not on Crashlytics), about 5-7% (Very large number) with this same error:
*** *** *** *** *** *** *** *** *** *** *** *** *** *** ***
pid: 0, tid: 18132 >>> com.xxx.xxx<<<

backtrace:
   #00 pc 0x000000000005c310
   #01 pc 0x0000000000058838 /data/data/com.xxx.xxx/app_pccache/5/7B8F7DD4852F73BBFA173EB6B41A78FEF0FC34F5/pcam.jar




We are using Google Mobile Ads SDK v21.3.0. When we found the error we were using Yandex Mobile Ads SDK v5.0.7, we tried to upgrade to v5.0.8 and target SDK 33 but the error persisted.
Please help us fix this, if we can't solve this we will probably have to remove Yandex Ads in future updates.
Thank you!

**Comment by mobile-ads-github** [comment]
Hello!
You mean v5.7.0 and 5.8.0, right? 
However we don't use native calls in our sdk. 
So we need crash stack trace and your App Id to check the problem. 
Thank you

**Comment by huyptmaxmobile** [comment]
Hi,
Sure, I have edited the versions.
I only have this short stack trace from Play Console of both apps
```
*** *** *** *** *** *** *** *** *** *** *** *** *** *** ***
pid: 0, tid: 18132 >>> com.xxx.xxx<<<

backtrace:
   #00 pc 0x000000000005c310
   #01 pc 0x0000000000058838 /data/data/com.xxx.xxx/app_pccache/5/7B8F7DD4852F73BBFA173EB6B41A78FEF0FC34F5/pcam.jar

```
